version: 2
updates:
  - package-ecosystem: "pip"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "Maven"
    # Files stored in `app` directory
    directory: "/src/advisor/tools/graviton-ready-java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"