name: Build Test

on:
  push:
    branches: 
    - main
    - release/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Run build and tests
      run: |
        ./test.sh
    
    - name: Code coverage
      run: |
        ./.venv/bin/python -m coverage report
  
  build-windows:
    
    runs-on: "windows-latest"
    
    steps:
    - uses: actions/checkout@v3

    - name: Prevent adding secrets to repo
      run: |
          git clone https://github.com/awslabs/git-secrets.git target
          cd target
          ./install.ps1
          echo "Git-secrets installation completed"
          git secrets --register-aws --global
          echo "Added aws secret templates"
          git secrets --scan -r ../
          echo "Repository scan completed"
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Run build and tests
      run: |
        .\Test.ps1
    
    - name: Code coverage
      run: |
        .\.venv\Scripts\coverage report